### ISSUE TITLE
Need basic build/compile instructions

### ISSUE THREAD

**Issue by Olliebrown** [kjems/uversioncontrol#2]
I'm eager to build the latest version of this package as the one that's available in the asset store is at least one major revision behind and does not work with Unity 2018.  I found the old Bitbucket repo which has some instructions on how to compile/build the package from source but the project was structured differently in that repo and included a visual studio solution that is not available in this latest form.

If you can add some simple compiling/building instructions that would take a user from the source code (available here) to using the package in Unity that would be super helpful!  Doesn't have to be comprehensive, you can assume anyone who winds up here is a seasoned programmer and may just need a nudge in the right direction (or maybe a link to some documentation on the Unity site somewhere that is relevant to these types of packages).

**Comment by Olliebrown** [comment]
I've found a way to get it to compile enough to debug and work through some issues.  Here's what I did:

- Get yourself an existing unity project, possibly with some simple assets, and make sure it is using .NET 4.x (Edit -> Project Settings -> Player -> Other Settings -> Configuration -> Scripting runtime version)
- Also, make sure to turn on visible meta files (Edit -> Project Settings -> Editor -> Version Control -> Mode)
- Import that project into an SVN repo (so you can experiment with the UVC extension right in that same project).
- Clone the uversioncontrol Git repo into a folder in the 'assets' directory of that same unity project.
- It's a bit of a version control tur-duck-en at this point but it should work.
- On startup, the editor will compile all of the modules defined with .asmdef files into DLLs and link them all together (you can find the DLLs and mdb files under the Library/ScriptAssemblies folder)

To edit the source and see your changes, it appears you have to quit the unity editor and restart it (this is what triggers re-compiling of the editor scripts).

Still not sure this is the best way of doing things but it seems to work!  Note that I am using the latest 2018 verison of Unity (2018.2.7f1 at the time of writing).

**Comment by kjems** [comment]
Hi Ollie,

I will use some of your description for setting up UVC.

Thanks,
Kristian
