### ISSUE TITLE
Working copies stored in a path with a space are not supported (windows 10, Unity 2018.2.7)

### ISSUE THREAD

**Issue by Olliebrown** [kjems/uversioncontrol#3]
I have a working copy of my repo stored in a path with a space.  This causes errors with the CommandLine execution system when the path is used as a parameter to an SVN command.  The space is neither quoted or escaped so it gets picked up as a separator between command arguments and the working copy path is truncated at the first space resulting in failure to execute.

I can avoid/work around this problem by simply avoiding paths with spaces but this is not so easy to do on computer systems where we do not have full control over the directory structure (servers, company issued laptops and desktop, my student's school issued laptops, etc).

I'm working to try and find a fix for this in the C# scripts myself but wanted to document it here as well.

**Comment by Olliebrown** [comment]
Hmm, well nevermind.  I can't reproduce this now.  I wonder if maybe it had been fixed in the head revision.  I was originally building the 2.3.1 version and then I switch to the HEAD revision and now I don't think it is happening any more.  i will confirm that for myself once more and if it's not the case I'll come back here and re-open this but looks like this was a false positive.  Sorry.

**Comment by olivier4321** [comment]
The error is still there, at least in the SetIgnore() function (if you answer "yes" when UVC asks you if you want to fix ignores).

```
string.Format("propset svn:ignore \"{0}\" {1}", assets.Aggregate((a, b) => a + "\n" + b), path)
```
should have quotes around {1}.
